### ISSUE TITLE
Regression in broccoli-asset-rewrite breaks asset URLs

### ISSUE THREAD

**Issue by mjuniper** [rickharrison/broccoli-asset-rev#98] opened 2016-06-28 17:30 UTC
See https://github.com/rickharrison/broccoli-asset-rewrite/issues/36

Perhaps you could revlock the broccoli-asset-rewrite dependency to v1.0.11?

**Comment by rickharrison** [comment] 2016-06-28 17:31
Going to close this as the issue is in rewrite. A failing test case would greatly help!

**Closed by rickharrison** 2016-06-28 17:31 UTC

**Comment by mjuniper** [comment] 2016-06-28 17:32
👍
